IsThere missing when using`-d` modifier
```
git-stats -d repositories/cadexmus2
/var/www/html/node_modules/git-stats/bin/git-stats:104
        if (!IsThere(GitStats.path)) {
             ^

ReferenceError: IsThere is not defined
```